jstimer.settings:
  type: mapping
  label: Settings
  mapping:
    jstimer_js_load_pages:
      type: string
    jstimer_js_exclude_pages:
      type: string
    jstimer_output_format:
      type: string
    jstimer_output_format_1:
      type: string
    jstimer_output_format_2:
      type: string
    jstimer_output_format_3:
      type: string
    jstimer_complete_statement:
      type: string
