<?php

/**
 * @file
 * Views better exposed forms altering. Custom color filter
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function biedconditie_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the biedconditie module.
    case 'help.page.biedconditie':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Views better exposed forms altering. Custom color filter') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
 #function biedconditie_theme($existing, $type, $theme, $path) {
 # return [
   # 'custom-exposed-form' => [
   #   'render element' => 'form'
   # ]
  # ];
# }

/**
 * Implements hook_views_data_alter().
 */
 #function biedconditie_views_data_alter(array &$data) {
 # if (isset($data['node__field_kleur_picker']['field_kleur_picker_color'])) {
 #   $data['node__field_kleur_picker']['field_kleur_picker_color']['filter']['id'] = 'custom_color_picker_filter';
 # }
# }

/**
 * Implementing hook_form_id_alter().
 */
function biedconditie_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  if ($form['#id'] = 'exposedform_voertuigenpagina_veiling_alle_wagens') {

    $children_fields = \Drupal\Core\Render\Element::children($form);
    // $form['#theme'] = 'custom-exposed-form';
    foreach ($children_fields as $id => $children_field) {
      if (isset($form[$children_field]['#attached']["drupalSettings"]) && isset($form[$children_field]['#attached']["drupalSettings"]['better_exposed_filters']) && isset($form[$children_field]['#attached']["drupalSettings"]['better_exposed_filters']['slider_options'])) {
        $slider_options = $form[$children_field]['#attached']["drupalSettings"]['better_exposed_filters']['slider_options'][$children_field];
        $id = $slider_options['id'];
        $min = $slider_options['min'];
        $max = $slider_options['max'];

        // Hide the input fields as we will now be using the custom markup
        // to display the values.
        $form[$children_field . '_wrapper'][$children_field]['min']['#attributes']['style'] = ['display: none;'];
        $form[$children_field . '_wrapper'][$children_field]['max']['#attributes']['style'] = ['display: none;'];

        // Hide the "AND" label for the max field
        unset($form[$children_field . '_wrapper'][$children_field]['min']['#title']);
        unset($form[$children_field . '_wrapper'][$children_field]['max']['#title']);

        $form[$children_field . '_wrapper'][$children_field]['min_custom'] = ['#markup' => "<span id='$id-custom-min' class='custom-min-max'>$min</span>"];
        $form[$children_field . '_wrapper'][$children_field]['max_custom'] = ['#markup' => " - <span id='$id-custom-max' class='custom-min-max'>$max</span>"];

        $form[$children_field . '_wrapper'][$children_field]['#prefix'] = "<div id='custom-filter-wrapper'>";
        $form[$children_field . '_wrapper'][$children_field]['#suffix'] = "</div>";
      }
    }
  }
}


/**
 * Implements hook_shs_js_settings_alter().
 */
function biedconditie_shs_js_settings_alter(&$settings_shs, $bundle, $field_name) {
  if ($field_name == 'field_merk') {
    $settings_shs['settings']['anyLabel'] = t(' - Auto merk - ');
    $settings_shs['display']['animationSpeed'] = 300;
    $settings_shs['parents']['defaultValue'][0][0] = t(' - Kies een type - ');

  }
  elseif ($field_name == 'field_regio') {
    $settings_shs['settings']['anyLabel'] = t(' - Regio - ');
    $settings_shs['display']['animationSpeed'] = 300;
  }
}

/**
 * Implements hook_views_data_alter().
 */
function biedconditie_views_data_alter(array &$data) {
  if (isset($data['node__field_kleur_picker']['field_kleur_picker_color'])) {
    $data['node__field_kleur_picker']['field_kleur_picker_color']['filter']['id'] = 'custom_color_picker_filter';
  }
}
