<?php
/**
 * @File
 * Custom module for Bid validate in Drupal 8.
 */

/**
 * Implementing hook_menu().
 */

use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_node_insert().
 */
function veiling_node_insert($entity) {

  if ($entity->getType() == 'veiling_invoer_particulieren' or $entity->getType() == 'veiling_invoer_handelaren') {
        $reserve = $entity->get('field_reserve')->value;
	      $elevation = $entity->get('field_min_elevation')->value;
	      $min = $reserve - $elevation;
    //Insert a custom table in the database. For drupal 9 insert from the container in stead of db_insert.$injected_database->
        $query = \Drupal::database()->insert('custom_bid_data');
    $query->fields(array(
    'nid' => $entity
        ->id(),
        'min' => $min,
  ))
    ->execute();
  }
}

function veiling_node_delete($entity) {

    $query = \Drupal::database()->delete('custom_bid_data');
    $query->condition('nid', $entity
          ->id())
          ->execute();
}

/**
 * Implementing hook_node_presave().
 */
function veiling_node_presave($entity) {
   if ($entity->getType() == 'veiling_invoer_particulieren' or $entity->getType() == 'veiling_invoer_handelaren' && $entity->getEntityTypeId() == 'node'){
    $in = $entity->get('field_expaire_time')->value;
    $NewDate=Date('Y-m-d\TH:i:s', strtotime("+".$in." days"));
    $entity->set('field_afteller',$NewDate);
      // Something has been configured very BADLY if i have to do this
     // to set node to published -@bl
    $entity->set('status', TRUE);
  }
}

/**
 * Implements hook_form_ID_alter().
 */
function veiling_form_comment_nu_kopen_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
        $form['field_koop_nu']['widget'][0]['value']['#title_display'] = 'none';
        $form['actions']['submit']['#value'] = 'Nu kopen';
        $form['actions']['preview']['#access'] = FALSE;
}
