<?php

/**
 * @file
 * Contains opbieden.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opbieden_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opbieden module.
    case 'help.page.opbieden':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Een opbied veld met instellingen') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opbieden_theme() {
  return [
    'opbieden' => [
      'render element' => 'children',
    ],
  ];
}




 

